[[package]]
nix = "bat-extras.core"
brew = "bat-extras"

[[package]]
nix = "claude-code"
brew = "claude-code"
type = "cask"

[[package]]
nix = "codex"
brew = "codex"
type = "cask"

[[package]]
nix = "copilot-language-server"
brew = false

[[package]]
nix = "delta"
brew = "git-delta"

[[package]]
nix = "github:helix-editor/helix"
brew = "helix"
type = "formula"
args = ["HEAD"]

[[package]]
nix = "home-manager"
brew = false

[[package]]
nix = "jujutsu"
brew = "jj"

[[package]]
nix = "github:nix-community/neovim-nightly-overlay"
brew = "neovim"
type = "formula"
args = ["HEAD"]

[[package]]
nix = "nixd"
brew = false

[[package]]
nix = "nixfmt-rfc-style"
# brew = "nixfmt"
brew = false

[[package]]
nix = "nodejs"
brew = "node"

[[package]]
nix = "tree-sitter"
brew = "tree-sitter-cli"

[[package]]
nix = "vectorcode"
brew = false
